terraform {
  required_version = "~> 1.0.0"
  // Setup backend for terraform, this is generated by the orchestration pipeline, do not modify.
  backend "s3" {
    encrypt        = true
    bucket         = "vts-nep-dev-terraform-remote-state"
    dynamodb_table = "vts-nep-dev-terraform-remote-state"
    key            = "new-project-template/environment/terraform.tfstate"
    region         = "ap-southeast-2"
    role_arn       = "arn:aws:iam::473411030665:role/devops-ca-admin"
  }
}