service_name                     = "${service_name}"
component_name                   = "${component_name}"
environment                      = "${environment}"
management_kms_arn               = "${management_kms_arn}"
application_state_config         = ${application_state_config}
cost_group                       = "${cost_group}"
created_by                       = "terraform: build pipeline"
owner                            = "${owner}"
parameter_store_values           = ${parameter_store_values}
