terraform {
  required_version = "1.0.0"

  // Setup backend for terraform, this is generated by the build pipeline, do not modify.
  backend "s3" {
    encrypt        = true
    bucket         = "${service_name}-${environment}-terraform-remote-state"
    dynamodb_table = "${service_name}-${environment}-terraform-remote-state"
    key            = "${service_name}/${component_name}/application/terraform.tfstate"
  }
}
