version: 0.2

env:
  variables:
    RELEASE_BUCKET_NAME: ${release_bucket_name}
    TERRAFORM_VERSION: ${terraform_version}
    TERRAFORM_RELEASE_ARTIFACT_NAME: "terraform-release-*-deploy.zip"
  exported-variables:
    - RELEASE_PIPELINE_NAME

phases:
  install:
    commands:
      - aws s3 cp --no-progress s3://$${RELEASE_BUCKET_NAME}/dependencies/bin/terraform-$${TERRAFORM_VERSION} terraform
      - chmod +x terraform
      - mv terraform /usr/bin
      - mkdir terraform-release
      - unzip `find . -name $TERRAFORM_RELEASE_ARTIFACT_NAME | sort | tail -1` -d terraform-release
      - >
        cat > terraform-release/terraform.tf << EOF
          ${terraform_tf}
        EOF
      - >
        cat > terraform-release/terraform.tfvars << EOF
          ${terraform_tfvars}
        EOF
  build:
    commands:
      - cd terraform-release
      - terraform init
      - terraform apply -auto-approve
  post_build:
    commands:
      - terraform output -json > remote-state.json
      - export RELEASE_PIPELINE_NAME=$(cat remote-state.json | jq -r .pipeline_name.value)
